let ImagePaths = [
  "../images/Alex Kidd - SNES - Last Action Hero - Jack Slater.png",
  "../images/autumn-icons-set-2827x2839x3x3-cc0.png",
  "../images/cartoon-ghost-399x432-cc0.png",
  "../images/Chris Hamons - PublicDomain - DungeonCrawl_ProjectUtumnoTileset-32x32.png",
  "../images/Chris Hamons - PublicDomain - ProjectUtumno_full-32x32.png",
  "../images/Chris Hamons - PublicDomain - ProjectUtumno_supplemental-32x32.png",
  "../images/CupMan-97184-103x113.png",
  "../images/CupMan-97184-RWWJ-64x64.png",
  "../images/Dark Elf Pixel Art - wizard spritesheet calciumtrice - 32x32.png",
  "../images/David-Jakubec - Character_spriteSheet-64x107.png",
  "../images/David_Jakubec-Land_Crash-spriteSheet-64x64in66x66.png",
  "../images/David-Jakubec - RWWJ Colors 1 - 64x107.png",
  "../images/Frog - Cartoonish - by Muzyun.png",
  "../images/GOD_OF_CODING-Background-for-Zombies-bg.png",
  "../images/haunted-house-at-sunset-2000x1411-cc0.png",
  "../images/Hyptosis-BombExploding.png",
  "../images/Hyptosis-hyptosis_til-art-batch-2-32x32.png",
  "../images/Hyptosis-hyptosis_tile-art-batch-1-32x32.png",
  "../images/Hyptosis-hyptosis_tile-art-batch-3-32x32.png",
  "../images/Hyptosis-hyptosis_tile-art-batch-4-32x32.png",
  "../images/Hyptosis-hyptosis_tile-art-batch-5.png",
  "../images/jack-o-lantern-136x125-cc0.png",
  "../images/Kutejnikov_PublicDomain-Wooden_boat-3x24x72.png",
  "../images/Lizard - Cartoonish - by Muzyun.png",
  "../images/Mandrake Sprite 256x256 354 Frames 18x20 Sprites - no Copyright Franks laboratory .png",
  "../images/Mushroom - Red - Cartoonish - by Adorelee.png",
  "../images/NicePng_2d-character-png_3483964.png",
  "../images/Pancakes - Cartoonish - By Lingerie.png",
  "../images/peace-and-love-bus-512x512-cc0.png",
  "../images/Pixel Art Adventurer Sprites - Dungeon_Tileset-32x32.png",
  "../images/scary-jack-o-lantern-1000x1000-cc0.png",
  "../images/Sithjester-JapaneseVillage02-Interior-32x32.png",
  "../images/Sithjester - meroko-32x48.png",
  "../images/Sithjester-steampunk_f12-32x52.png",
  "../images/Sithjester-steampunk_f12-RWWJ-64x64.png",
  "../images/Snake - Green - Cartoonish - by Muzyun.png",
  "../images/SNES - Super Mario World.png",
  "../images/Snowflake Spritesheet - Alca.tv via Dan Shiftman - 32x32.png",
  "../images/Snowflake Spritesheet - Alca.tv via Dan Shiftman - 64x64.png",
  "../images/SnowFlakesSpriteSheet-DanShiftman-f16.png",
  "../images/Spriters Resource - PC Computer - Angry Video Game Nerd Adventures - Spirits - 48x64.png",
  "../images/Tic Tac Toe - O.png",
  "../images/Tic Tac Toe - X.png",
  "../images/Tilation - Potions - 64x64.png",
  "../images/TradnuxTeej - stripsheet_charbase_template.png",
  "../images/Wolfenstein 33 - Wall Textures Rip - 10151 - 64x64 plus 1.png",
  "../images/Wolfenstein 33 - Wall Textures Rip - 1375 - 64x64.png"
]
